[package]
name = "nightjar-daemon"
description.workspace = true
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
nightjar-core.workspace = true
nightjar-config.workspace = true
nightjar-runner.workspace = true
nightjar-schedule.workspace = true
nightjar-store.workspace = true
anyhow.workspace = true
jiff.workspace = true
libc.workspace = true
uuid.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true
