[package]
name = "nightjar-core"
description.workspace = true
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
jiff.workspace = true
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
